In [1]:
import numpy as np

arr = np.array([1,2,3])

print(arr)

type(arr)

[1 2 3]


numpy.ndarray

In [2]:
print(np.__version__)

1.26.4


In [3]:
__ * 2

''

In [53]:
arr1 = np.array([[1,2,3],[3,3,3]])
arr2 = np.array([1,2,3], ndmin = 4)

print(arr1[0][1])
print(arr1.ndim)

print(arr2)
print(arr2.ndim)

2
2
[[[[1 2 3]]]]
4


In [17]:
print(arr1[0])
print(arr1[1])

[1 2 3]
[3 3 3]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) # inicio:fim-1

[2 3 4 5]


In [20]:
vetor = np.array([1,2,3,4,5])

copia = vetor.copy()

vista= vetor.view()

vetor[0] = 3.14

print(vetor)
print(copia)
print(vista)

[3 2 3 4 5]
[1 2 3 4 5]
[3 2 3 4 5]


In [21]:
print(copia.base)

None


In [22]:
print(vista.base)

[3 2 3 4 5]


In [23]:
print(vetor.base)

None


In [24]:
# Mede as dimensões do array
print(arr2.shape)

(1, 1, 1, 3)


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(6, 2)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [32]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr4.reshape(-1)
newarr1 = arr4.reshape(6)

print(newarr)
print(newarr1)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [31]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [33]:
for x in np.nditer(arr4):
  print(x)

1
2
3
4
5
6


In [34]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]): #trocar : por 1 --> resultado: 5,7
  print(x)

1
3
5
7


In [36]:
print(np.ndenumerate(arr))

In [37]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


# Concatenando Arrays Numpy

In [46]:
arr_a = np.array([1,2,3])

arr_b = np.array([4,5,6])

arr_c = np.concatenate((arr_a, arr_b), axis=0)

arr_d = np.stack((arr_a, arr_b), axis=0)

print(arr_c)

print(arr_d)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [47]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [48]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
2
(6, 3)


In [51]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


# Filtrando e lembra do sort

In [54]:
arr = np.array([41, 42, 43, 44])

x = arr[[True, False, True, False]]

print(x)

[41 43]


# Tratando de números Random